#!/usr/bin/env bash
# Installs and configures nginx on a server

apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
