#!/usr/bin/env bash
# Fixes a container's nginx and ensures it is running on port 80

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
