#!/usr/bin/env bash
# Fixes a container's nginx and ensures it is running on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /run/nginx.pid
